### ISSUE TITLE
Add Column number variable?

### ISSUE THREAD

**Issue by KeyWorksRW** [rioj7/command-variable#1]
VS Code provides the variable \${lineNumber}, but does not provide a column number variable. I have an external program that I run as a task which could do an auto-selection if no selection string was provided (${command:extension.commandvariable.selectedText}), but while I can get the filename and line number, the lack of a column number prevents me from going any further with the app.

If the VS API provides that information, could you provide a variable to return the column number?

**Comment by rioj7** [comment]
@KeyWorksRW The feature is implemented with slightly different names in v0.4.0
