### ISSUE TITLE
Transform on ${workspaceFolder} requires a file to be open

### ISSUE THREAD

**Issue by pm185240** [rioj7/command-variable#10]
After opening a folder, with the below task and input setup in tasks.json (inside .vscode), the transform input produces the result "Unknown" if no files are open, and Command Variable extension fires a "No Editor" error box.  Both are resolved if any file is opened in the editor pane.

Using the raw VSCode variable ${workspaceFolder} produces the path of the opened Folder regardless if any files are opened in the editor.

This was tested on VSCode operation on a host system folder and through Remote - SSH folders to a Linux VM
VSCode version : 1.53.2
Extension Version: 1.12.0
OSs tested on:
 Host - Windows 10
 Remote - Centos 7.9

To reproduce, open a folder with VSCode and replace tasks.json with the below, close all files in editor and execute echo task:
 Output is: 
```
> Executing task: echo Unknown  && echo path\of\vscode\folder<
Unknown
path\of\vscode\folder
```

Open any file in the folder (tasks.json will work) and run echo task again
Output is:
```
> Executing task: echo path\of\vscode\folder && echo path\of\vscode\folder <
path\of\vscode\folder
path\of\vscode\folder
```

where the path is the path of your VSCode folder

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
      {
        "label": "echo",
        "type": "shell",
        "command": "echo ${input:makeRelDir} && echo ${workspaceFolder}",
        "problemMatcher": []
      }
    ],
    "inputs": [
      {
        "id" : "makeRelDir",
        "type":"command",
        "command": "extension.commandvariable.transform",
        "args":{
          "text": "${workspaceFolder}",
          "find": "(.*)",
          "replace": "$1"
        }
      }
    ]
}
```

**Comment by rioj7** [comment]
@pm185240  What do you expect to return if you have a Multi Root Workspace without any open editor?

**Comment by pm185240** [comment]
@rioj7 Thats a good question.  I wasn't using Multi-root Workspaces when dealing with this issue.
I ran a quick test with my VSCode where I had 2 folders open, one with tasks.json and one without.  The task just echo'd the VSCode ${workspaceFolder}.  With or without an editor opened it would evaluate to the folder the task was run from.

Is it possible for Command-variable to work like VSCode's own variable?  The workspace of the task/input is used?

**Comment by rioj7** [comment]
@pm185240  I have the single folder workspace implemented (I'm writing unit tests to be sure I haven't broken anything, you have to emulate/program all the user actions ;-|, and I'm not used to this JS test framework )

Sounds logical to return the workspace that `tasks.json` is in.

I have to find out if I can determine the workspace that is running this task/launch configuration.

Would it be a big deal if the user has to annotate the variable with part of the directory path to determine the workspace folder. 

Like `${workspaceFolder#/server/#}` (`#` is the separator)

This makes it possible to run a task from a different workspace then where the current file is stored.

**Comment by pm185240** [comment]
@rioj7 great! Hopefully VSCode exposes those inner-workings for you.

I don't quite follow your annotate explanation.  Are you meaning if I had Multi-workspace of folder /server/somefolder and /client/someotherfolder, I could (or have to?) specify ${workspaceFolder#/server/#} to get the server folder path?  
I think that makes sense (especially if VSCode does not expose an easy-enough way to get the workspace from the input/task running).

**Comment by rioj7** [comment]
VSC already has a syntax for: [Variables scoped per workspace folder](https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder)

`${workspaceFolder:Client}`

It uses the name of the Workspace,

I will adopt this syntax. VSC does not replace variables in strings in the `input` section

**Comment by rioj7** [comment]
@pm185240  Implemented in v1.14.0. Now most functionality is under test with and without editor open.

**Comment by pm185240** [comment]
@rioj7 Awesome, thanks.
I gave it a test (on 1.16 and 1.14) and ran into an issue.

When using the command "extension.commandvariable.transform" via VSCode Remote - SSH, I get an error of "command 'extension.commandvariable.transform' not found"
This does not happen when run VSCode locally on the machine I was remoting to, with v1.16.
This does not occur when I revert back to v1.13 and run Remotely.
Should I open a new ticket?  And do you need more information or logs?

Thanks

**Comment by rioj7** [comment]
@pm185240 I have never used VSC Remote SSH. I will try it out from Windows to Linux (VM). Something to read before bedtime.

**Comment by rioj7** [comment]
@pm185240

Pretty cool that Remote Development over SSH.

First had to reset the VM password via the Ubuntu recovery boot (bookmarked!)

I had to debug the extension in the Remote host to get a hint of the cause. VSC and VSC Server run different versions of Node.js. VSC Server does not support the `??` and `?.` operators.

Try version v1.16.1

**Comment by pm185240** [comment]
Works like a charm!  Thanks a lot for the quick turnarounds and great features!
