### ISSUE TITLE
Returning empty string on pickfile (and possibly other pick commands)

### ISSUE THREAD

**Issue by csghone** [rioj7/command-variable#12]
Usecase:
I have a program which takes in two args - two files actually.
I am using `extension.commandvariable.file.pickFile` for these in my launch.json.
Sometimes, the programs can infer the second arg from the first one.
In this case, I want to send an empty string as return value of `extension.commandvariable.file.pickFile` rather than manually picking the auto-inferred file.

Do let me know if you have any questions on these.

PS: This extension is brilliant! Thank you!

**Comment by rioj7** [comment]
@csghone I will add a property to the arguments that will add an entry in the list that will return an empty string

**Comment by rioj7** [comment]
@csghone  the extra property is

```
 "addEmpty" : true
```

**Comment by csghone** [comment]
Thank you! @rioj7
