### ISSUE TITLE
please add LICENSE file

### ISSUE THREAD

**Issue by GitMensch** [rioj7/command-variable#14]
Ideally via GitHub as described in the docs [adding a license to a repository][1].
Additional please also add a copyright and license note to extension.js, possibly similar as found in the uuid.js.

[1]:https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by rioj7** [comment]
I see no need for that

**Comment by GitMensch** [comment]
I totally agree about the hashes. The tags are normally the way how I get those, if you have another clever way to get the hash for a specific version then I'm interested to learn about that.

**Comment by klausholstjacobsen** [comment]
Does that mean that people are free to use the extension as they see fit?

Regards
Klaus

**Comment by GitMensch** [comment]
No, that means that people have to assume that the license identifier in package.json is both correct and applies to all files of this repository. (adding the license file would be so easy, even possible using the "UI to choose wich" option...)

**Comment by klausholstjacobsen** [comment]
Ahhh yes, found it, thanks!
