### ISSUE TITLE
Is there a reason to use an old uuid.js?

### ISSUE THREAD

**Issue by GitMensch** [rioj7/command-variable#15]
Just wondering because the version 1.8.0 used here says "deprecated, no longer maintained" while the link in the README [points to a current 4.2.8](https://www.npmjs.com/package/uuidjs).

**Comment by rioj7** [comment]
@GitMensch  The v1.8.0 is the version of the `command-variable` extension as named in the package.json of that commit, in v1.8.0 I added the UUID command using uuid.js v4.2.0 as mentioned in the file

**Comment by GitMensch** [comment]
I see, then it isn't as bad as I've originally thought. But there's still the question "is there an reason not to use 4.2.8 which is not deprecated"? If not I suggest having a look at updating uuid.js.

**Comment by rioj7** [comment]
@GitMensch I will update the uuid.js in one of the next releases. 

Just looked at the repo for UUID and v4.2.0 was released on 2018-12-03.
I have added UUID in 2020-12 so I should have gotten v4.2.6 by `npm install`

**Comment by rioj7** [comment]
@GitMensch updated to uuid.js v4.2.8 and verified it works with Remote SSH. You can now output different formats
