### ISSUE TITLE
please tag old and new versions

### ISSUE THREAD

**Issue by GitMensch** [rioj7/command-variable#17]
Which allows for an easier compare, bisect (in case that's ever needed) and for new versions possibly also allows automated build/publish if you ever want to add that.

If you want me to I'd prepare a script to add the old versions, just would need to know the git hashes of those (or a note if the last thing you did before a release is updating package.json, in this case I can take the hashes from its version history).

**Comment by rioj7** [comment]
All those operations can be done with hashes I see no need to tag every commit

**Comment by GitMensch** [comment]
I totally agree about the hashes. The tags are normally the way how I get those, if you have another clever way to get the hash for a specific version then I'm interested to learn about that.

**Comment by rioj7** [comment]
@GitMensch  `git log --one-line`

**Comment by GitMensch** [comment]
I guess you mean `git log --pretty=oneline` (the other one is not recorgnized).
I now see what you mean: this repo is quite special as _each_ commit is a new version - in this case I totally agree that it isn't useful to add another tag on top. Thank you for the explanation.
