### ISSUE TITLE
"Unknown" output from file.content command

### ISSUE THREAD

**Issue by dfarley1** [rioj7/command-variable#19]
I'm trying to use your extension to make retrieving complex debugger args simpler. I have a `preLaunchTask` that outputs the args I want to pass to the debugger to `/depot/out/cur/vscode-debugArgs`. However, when the launch target (or any task) tries to read the file it fails and I just get `"Unknown"`.

Since all your error cases in file reading result in the same value and there's no logging I can't tell where things are going wrong. I've tried using an absolute path (`/depot/out/cur/vscode-debugArgs`) as well as relative to the workspace root (`out/cur/vscode-debugArgs`). Any ideas?

tasks.json:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "getArgsTask",
            "type": "shell",
            "command": "echo ${input:getArgsInput}",
            "problemMatcher": []
        }
    ],
    "inputs": [
        {
            "id": "getArgsInput",
            "type": "command",
            "command": "extension.commandvariable.file.content",
            "args": {
                "fileName": "/depot/out/cur/vscode-debugArgs"
            }
        }
    ]
}
```

Task output:
```
> Executing task in folder depot: echo Unknown <

Unknown

Terminal will be reused by tasks, press any key to close it.
```

In a shell:
```
danf@depot /depot $ ls -lsa /depot/out/cur/vscode-debugArgs 
4 -rw-r--r-- 1 danf danf 7 Apr 21 17:21 /depot/out/cur/vscode-debugArgs
danf@depot /depot $ cat /depot/out/cur/vscode-debugArgs 
foobar
```

**Comment by rioj7** [comment]
@dfarley1 I had implemented a new feature (needs to be further tested) but it made it to the published extension.

Can you try it with version v1.16.2, you can download that version from the **Version History** tab on the [Marketplace page](https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable)

I will add a debug log to the `file.content` command. An also remove the new feature from the published extension.

**Comment by rioj7** [comment]
@dfarley1 In version 1.18.3 I have added the debug statements.

Modify the `args` parts to:

```
            "args": {
                "fileName": "/depot/out/cur/vscode-debugArgs",
                "debug": true
            }
```

1. Show Console: **Help** > **Toggle Developer Tools**
2. Clear Console
3. Run Task

You should see these debug statements in the console if there are no errors:

```
[Extension Host] commandvariable.file.content: debug logs enabled
[Extension Host] commandvariable.file.content: readFileContent: from: /depot/out/cur/vscode-debugArgs
[Extension Host] commandvariable.file.content: readFileContent: after variable substitution: /depot/out/cur/vscode-debugArgs
[Extension Host] commandvariable.file.content: readFileContent: test if file exists: /depot/out/cur/vscode-debugArgs
[Extension Host] commandvariable.file.content: readFileContent: read file before utf8 conversion
[Extension Host] commandvariable.file.content: content: foobar
[Extension Host] commandvariable.file.content: content to value: foobar
```

Does the file contain a newline? File size is 7 bytes and `foobar` is 6 characters.

Does the file contain a BOM code at the start? Use `od -x /depot/out/cur/vscode-debugArgs` to examine.

**Comment by dfarley1** [comment]
> Does the file contain a newline? File size is 7 bytes and foobar is 6 characters.

In that instance yes, but I tried both cases without success.

> Does the file contain a BOM code at the start? Use od -x /depot/out/cur/vscode-debugArgs to examine.

I'm generating the output with a little Go script and using Bash in another Task to put it in a file:
```
        {
            "label": "writeArgsTask",
            "type": "shell",
            "command": "/depot/test/gen_args -w ${input:filePicker} > out/cur/vscode-debugArgs",
            "problemMatcher": []
        }
```
```
danf@depot /depot $ od -x out/cur/vscode-debugArgs
0000000 6f66 626f 7261 000a
0000007
```

I installed v1.18.3 and ran my `getArgsTask` task, I get one of two outputs and I can't tell why:
```
{message: "Command in container failed: cat /proc/4270/environ", code: 1, stdout: "", stderr: "cat: /proc/4270/environ: No such file or directory↵"}
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
```
or 
```
  ERR Could not find pty with id "2": Error: Could not find pty with id "2"
    at g._throwIfNoPty (/home/depot/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/platform/terminal/node/ptyHostMain.js:12:41804)
    at g.shutdown (/home/depot/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/platform/terminal/node/ptyHostMain.js:12:40226)
    at Object.call (/home/depot/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/platform/terminal/node/ptyHostMain.js:11:8237)
    at u.onPromise (/home/depot/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/platform/terminal/node/ptyHostMain.js:10:44099)
    at u.onRawMessage (/home/depot/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/platform/terminal/node/ptyHostMain.js:10:43458)
    at /home/depot/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/platform/terminal/node/ptyHostMain.js:10:42711
    at w.fire (/home/depot/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/platform/terminal/node/ptyHostMain.js:8:1836)
    at process.E (/home/depot/.vscode-server/bin/3c4e3df9e89829dce27b7b5c24508306b151f30d/out/vs/platform/terminal/node/ptyHostMain.js:6:30258)
    at process.emit (events.js:315:20)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
```

Maybe it's worth noting that my workspace is inside a Docker container? Does your extension not support that? I'm not seeing any output from the extension in the dev console or the Extension Host Output.

**Comment by dfarley1** [comment]
I just noticed that I switched from absolute to relative at some point in my testing, my OP has `/depot/out/cur/vscode-debugArgs` which appears to work now. So maybe this whole thing was my fault...? I was testing with `/tmp/vscode-debugArgs` at some point as well, maybe it doesn't like paths outside the workspace?

**Comment by rioj7** [comment]
@dfarley1 

I will add a notice in the doc for full pathnames. Everything in VSC is done with full pathnames to be independent of the current working directory. Just look at the SO questions of people who do not have a clue what a current working directory is or what its value is.

VSC uses full pathnames because the terminal is having a different current working directory than the VSC executable where the extension is running.

In the doc you see an example of a file in `c:\temp`, not a likely workspace folder.

In your generation task you should make the output file path a full pathname to be sure you know where it will end.

I don't use Docker, I test VSC remote with SHH to an Ubuntu Virtual Machine in VirtualBox.

If this solves the issue you can close it.
