### ISSUE TITLE
How to select the match of a regex?

### ISSUE THREAD

**Issue by jepzen** [rioj7/command-variable#20]
Hi

I am triyng to get a part of a full path file name Ex.

/mnt/c/Users/me/code/app_root/engines/my_engine/spec/requests/api/api_spec.rb

I want to extract the "my_engine" part.

First try

```
 {
      "id": "ENGINE_NAME",
      "type": "command",
      "command": "extension.commandvariable.transform",
      "args": {
        "text": "${file}",
        "find": "(?<=engines\/)(.*)(?=\/spec)",
        "replace": "",
      }
    },
```

But this replace the part it finds only, not the whole string. So ending up with 

/mnt/c/Users/me/code/app_root/engines//spec/requests/api/api_spec.rb

Then I tried to split up into two parts. First get rid of the beginning of that path then the last 

```
 {
      "id": "remove_engines",
      "type": "command",
      "command": "extension.commandvariable.transform",
      "args": {
        "text": "${input:remove_spec}",
        "find": "(.*?)engines\/",
        "replace": "",
      }
    },
 {
      "id": "remove_spec",
      "type": "command",
      "command": "extension.commandvariable.transform",
      "args": {
        "text": "${file}",
        "find": "\/spec\/.*",
        "replace": "",
      }
    },
```
But I has no luck to read the ${input:remove_spec} inside the remove_engines command

It might be RegEx skills that sucks, but It would be nice with select the match from regex not replace. Or maybe you can suggest a workaround?

**Comment by rioj7** [comment]
@jepzen 

What the command does is: `find` the regex and replace the matched text with `replace`

So match the whole string and replace it with the capture group you want

```
    {
      "id": "ENGINE_NAME",
      "type": "command",
      "command": "extension.commandvariable.transform",
      "args": {
        "text": "${file}",
        "find": ".*/engines/(.*)/spec/.*",
        "replace": "$1"
      }
    },
```

**Comment by terryaney** [comment]
> "text": "${input:remove_spec}",

Was this working for you?  When I run `extension.commandvariable.transform` against `${input:foo}` where `foo` is a `pickStringRemember`, transform simply receives the literal text `${input:foo}` instead of evaluating/expanding the input.

**Comment by rioj7** [comment]
@terryaney I do not support `${input}` variables because I have no clue where the input variable is to be found. VSC knows from which place the command is called, the command has no clue and also can't determine. If you want to use such a stepped construct you should use the variable versions (some alternative of input vars) of the commands and supply the arguments in the arguments of the calling command (see the doc for variables)
