### ISSUE TITLE
Use `pickFile` as input of `file.content` `fileName`

### ISSUE THREAD

**Issue by renyhp** [rioj7/command-variable#22]
If I understand correctly, issue #21 and its fix makes it possible to use a `pickString` as an input of `file.content` `fileName`. Is it possible to make `pickFile` work as that input as well? In practice I have a directory of key-value files, and I would like to be prompted for which file should be used as list of key value pairs. (Right now my workaround is that I always pick from a single file which is actually a symlink to the file I want to use, and I have a task that creates and edits that symlink by prompting me for the file via `pickFile`.)

**Comment by rioj7** [comment]
@renyhp Try v1.23.0.

Fixed in  9986056

**Comment by renyhp** [comment]
@rioj7 Thanks that's very nice! Unfortunately it doesn't fit with my personal use-case. I have multiple arguments in a single `environ` file, which correspond to multiple inputs taken from the same `environ` file. Putting `${pickFile:environ}` in all `file.content`s results in VSCode asking me multiple times which file to use. Is there a way to ask for the file once and reuse that one for multiple inputs? Thanks a lot!

**Comment by rioj7** [comment]
@renyhp Try v1.24.0 I have added a property [`keyRemember`](https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable#file-content-multiple-key-valuesproperties)
