### ISSUE TITLE
Enable as web extension?

### ISSUE THREAD

**Issue by whilp** [rioj7/command-variable#25]
This extension does not advertise compatibility with VS Code's new(ish) web mode:

https://code.visualstudio.com/api/extension-guides/web-extensions

While much of the functionality might make little sense in the pure browser (ie, no shell) mode, other uses might still be...useful. For example, I had hoped to use command-variable to expand `extension.commandvariable.dateTime` in a command to create a new file. That might (should?) be doable w/o node.

**Comment by rioj7** [comment]
@whilp I have added a few more commands to the web extension
