### ISSUE TITLE
relativeFileDots

### ISSUE THREAD

**Issue by wpalfi** [rioj7/command-variable#26]
Could you please add `relativeFileDots`?

Reason: Launching python modules with `relativeDirDots` fails if the module is in the workspace folder:

E.g.
- workspace
  - sub
    - foo.py
  - bar.py  

```
${relativeDirDots}.${fileBasenameNoExtension}":
sub.foo
.bar => fails with "Relative module names not supported"

${relativeFileDots}:
sub.foo
bar
```

**Comment by rioj7** [comment]
@wpalfi I have added the following 2 commands

* `file.relativeFileDots`
* `file.relativeFileDotsNoExtension`

**Comment by wpalfi** [comment]
Great, just tested it, thanx!
Maybe you also want to replace relativeDirDots by  relativeFileDotsNoExtension in the readme-example.
