### ISSUE TITLE
 extension.commandvariable.selectedText

### ISSUE THREAD

**Issue by Anobium** [rioj7/command-variable#27]
"args": ["${extension.commandvariable.selectedText}"

I need to extract the selectedText from my source to pass the selectedText to a Help system.
Just cannot get a result.

            {
              "label": "echo",
              "type": "shell",
              "command": "echo",
              "args": ["Evan",
                "${extension.commandvariable.selectedText}"
              ]
            },

Shows nothing on terminal.

I have installed the extension in the user environment and it shows as an extension.

Any hints.

**Comment by rioj7** [comment]
@Anobium  You have to use an `${input}` variable in the task and the command in the input-variable

https://code.visualstudio.com/docs/editor/variables-reference#_input-variables

**Comment by Anobium** [comment]
Thank you
