### ISSUE TITLE
Remove src folder in path

### ISSUE THREAD

**Issue by fortierq** [rioj7/command-variable#29]
Hello,

My Python project is like this:
```
├── src
│   ├── a
│   │   ├── a.py
│   ├── b
│   │   ├── b.py
```
In b.py, I would like to import this way:
```python
import a.a
```
However, the following launch configuration adds `-m src.b.b` to the run command (relative to the root) which would require all the imports to be `import src.a.a`.
```
"module": "${command:extension.commandvariable.file.relativeFileDotsNoExtension}",
```
How to remove the first folder, to get `-m b.b` instead of `-m src.b.b` ? I tried this but it does not work (command command:extension.commandvariable.file.relativeFileDotsNoExtension#src. not found):
```
"module": "${command:extension.commandvariable.file.relativeFileDotsNoExtension#src.}",
```

**Comment by rioj7** [comment]
@fortierq 

You can use the `${command:name}` variable in the command `extension.commandvariable.transform` in v1.32.0 (commit bd50915)

```
    "module": "${input:relativeNoExtDotsBaseOff}",

........

  "inputs": [
    {
      "id": "relativeNoExtDotsBaseOff",
      "type": "command",
      "command": "extension.commandvariable.transform",
      "args": {
        "text": "${command:extension.commandvariable.file.relativeFileDotsNoExtension}",
        "find": "^[^.]+\\."
      }
    }
  ]
```
