### ISSUE TITLE
[1.34.0] command 'extension.commandvariable.pickStringRemember' not found

### ISSUE THREAD

**Issue by rdev34** [rioj7/command-variable#30]
When updating to `1.34.0`, a workspace configuration file that is working for `1.33.0` now produces this error:
![image](https://user-images.githubusercontent.com/12753141/162255346-a270d42d-2b8d-49a5-89cf-8da377098ddb.png)

If you have trouble reproducing, then I would be glad to get you more information on my specific workspace config file. I would guess this is just a global issue though with using `pickStringRemember`

**Comment by rioj7** [comment]
@rdev34 I just updated that command to also read from file, it can only happen if you use the command in a Web environment, I had to add an `if` statement to conditionally define it for the web.

**Comment by rioj7** [comment]
@rdev34 For a temporary workaround you can download and install v1.33.0 from the Marketplace

**Comment by rioj7** [comment]
@rdev34 found the cause, cherry picking in git and publishing the untested development with `vsce`.

In v1.34.1 I have published the version as found on git, and no longer shows the error

**Comment by rdev34** [comment]
Thank you! I can confirm my workspace file is working again on v1.34.1
