### ISSUE TITLE
Remember pick since 1.36.1 not working anymore

### ISSUE THREAD

**Issue by JL1709** [rioj7/command-variable#34]
Given the following example (slightly modified from the README)
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Pylint",
      "type": "shell",
      "command": "pylint ${input:selectDir}"
    }
  ],
  "inputs": [
    {
      "id": "selectDir",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "key": "path", (---------- NEW ----------)
        "description": "Which directory to Lint?",
        "options": [
          ["Rerun task with last pick", "${remember:path}"],
          ["All", "src/"],
          ["Pick directory", "${pickFile:directory}"]
        ],
        "default": null,
        "pickFile": {
          "directory": {
            "description": "Which directory?",
            "include": "src/**/*.{py}",
            "showDirs": true,
            "keyRemember": "path"
          }
        }
      }
    }
  ]
},
(---------- NEW START -----------)
{
    "id": "rememberInput",
    "type": "command",
    "command": "extension.commandvariable.rememberPick",
    "args": {
        "key": "path"
    }
}
(---------- NEW END ----------)
```
To make the option `["All", "src/"]` also work for `["Rerun task with last pick", "${remember:path}"]`, and be able to use the pick also in other tasks I have inserted the above marked with (NEW). This worked fine for version 1.36.0 but since the update to 1.36.1 it isn't working anymore (I just get `"> Executing task: pylint ${remember:path} <"` when I rerun the task).
Is there now another way to do it?

**Comment by rioj7** [comment]
@JL1709 use v1.37.0

* add property `"rememberTransformed": true`
* remove property `"default": null`  
  you should be able to Escape the pickString
* replace `rememberPick` with `remember`
* don't specify a `key` for the `pickFile`, or at least not `path`

<pre><code>{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Pylint",
      "type": "shell",
      "command": "pylint ${input:selectDir}"
    }
  ],
  "inputs": [
    {
      "id": "selectDir",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "key": "path",
        "description": "Which directory to Lint?",
        "options": [
          ["Rerun task with last pick", "${remember:path}"],
          ["All", "src/"],
          ["Pick directory", "${pickFile:directory}"]
        ],
        <strong>"rememberTransformed": true,</strong>
        "pickFile": {
          "directory": {
            "description": "Which directory?",
            "include": "src/**/*.{py}",
            "showDirs": true
          }
        }
      }
    }
  ]
},
{
    "id": "rememberInput",
    "type": "command",
    "command": "extension.commandvariable.<strong>remember</strong>",
    "args": {
        "key": "path"
    }
}
</code></pre>

**Comment by JL1709** [comment]
First, thanks for the quick help. But I have encountered problems when exiting multiple tasks when they are connected in series in another task. Let's say I want to start not only Pylint, but also Cpplint. Therefore I have to create a task 'Lint all' that first gets user input and than run the linters with the remembered input. When trying to escape here, the task still gets executed with the last remembered input instead of quitting. Example below:
´´´
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Lint all",
            "dependsOrder": "sequence",
            "dependsOn": [
                "Get user input",
                "Lint all with last user input",
            ],
            "problemMatcher": []
        },
        {
            "label": "Get user input",
            "type": "shell",
            "command": ": ${input:selectDir}",
            "problemMatcher": [],
            "presentation": {
                "echo": false,
            }
        },
        {
            "label": "Lint all with last user input",
            "dependsOn": [
                "Pylint with last user input",
                "Cpplint with last user input",
            ],
            "problemMatcher": []
        },
        {
            "label": "Pylint with last user input",
            "type": "shell",
            "command": "pylint ${input:rememberInput}",
            "problemMatcher": []
        },
        {
            "label": "Cpplint with last user input",
            "type": "shell",
            "command": "cpplint --recursive ${input:rememberInput}",
            "problemMatcher": []
        },
        {
            "label": "Pylint",
            "type": "shell",
            "command": "pylint ${input:selectDir}",
            "problemMatcher": []
        },
        {
            "label": "Cpplint",
            "type": "shell",
            "command": "cpplint --recursive ${input:selectDir}",
            "problemMatcher": []
        }
    ],
    "inputs": [
        {
            "id": "selectDir",
            "type": "command",
            "command": "extension.commandvariable.pickStringRemember",
            "args": {
                "key": "path",
                "description": "Which directory to Lint?",
                "options": [
                    [
                        "Rerun task with last pick",
                        "${remember:path}"
                    ],
                    [
                        "All",
                        "src/"
                    ],
                    [
                        "Pick directory",
                        "${pickFile:directory}"
                    ]
                ],
                "rememberTransformed": true,
                "pickFile": {
                    "directory": {
                        "description": "Which directory?",
                        "include": "src/**/*.{py}",
                        "showDirs": true
                    }
                }
            }
        },
        {
            "id": "rememberInput",
            "type": "command",
            "command": "extension.commandvariable.remember",
            "args": {
                "key": "path"
            }
        }
    ]
}
´´´
It would be nice if a clean escape would be possible.
