### ISSUE TITLE
create a workspace last folder variable

### ISSUE THREAD

**Issue by fr43nk** [rioj7/command-variable#35]
Hi,
I'm using workspaces a lot. There I have a bunch of paths configured to be part of that workspace.
Those paths have one base folder in common. My request now is, to have a variable which contains the folder name after the base folder. Like so:
```
"folders": [
		{
			"path": "d:\\dev_01\\common"
		},
		{
			"path": "d:\\dev_01\\technical"
		},
	]
```
For this example, a variable that just returns `common` or `technical` depending on the path of the open file.

Best regards,
Frank

**Comment by fr43nk** [comment]
Hi,

sadly it is not the right one. This is the first folder of my workspace path entries `common` in this example and not `technical`. Although the called filed is located in the last mentioned one. 

best

**Comment by rioj7** [comment]
@fr43nk  v1.38.0 has 2 new commands

- `extension.commandvariable.workspace.folderBasename`: basename of workspace root of current file
- `extension.commandvariable.workspace.folder`: workspace root of current file

**Comment by fr43nk** [comment]
Thanks a lot. Works great. 

Best regards.
