### ISSUE TITLE
Possibility to check if UI has been escaped in compound task/launch

### ISSUE THREAD

**Issue by rioj7** [rioj7/command-variable#36]
Feature asked as a result of #34 [comment-link](https://github.com/rioj7/command-variable/issues/34#issuecomment-1172186916)

In a compound task is it possible to prevent the execution of the next task if we Escape a UI (Pick/Prompt) in current task.

* every UI shown stores the Escape status (true/false)
* every UI and remember have a property `checkEscapedUI`, if true check the Escape status, if status is true behave as Escaped.  
  Do not set this property on the UI of the first task in the compound task. Or it will depend on the Escape status of a previous run.

**Comment by rioj7** [comment]
@JL1709 use v1.39.0

See the example with the property [checkEscapedUI](https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable#checkescapedui)

**Comment by JL1709** [comment]
@rioj7 Thanks a lot, works fine.
