### ISSUE TITLE
Find/replace in transform works only for the first occurence in the string

### ISSUE THREAD

**Issue by ziki77** [rioj7/command-variable#38]
This command

      {
        "id": "test",
        "type": "command",
        "command": "extension.commandvariable.transform",
        "args": {
          "text": "foo.foo.foo",
          "find": "foo",
          "replace": "bar",
          }
      },

called in this task

      {
        "label": "test",
        "group": "test",
        "options": {
          "shell": {
              "executable": "C:\\WINDOWS\\System32\\bash.exe",
              "args": [
                  "-c"
              ]
          },
          "cwd": "${workspaceFolder}"
        },
        "type": "shell",
        "command": "echo",
        "args": [
            "${input:test}",
        ],
        "problemMatcher": [],
      },

gives this output:

bar.foo.foo
Terminal will be reused by tasks, press any key to close it.

Is there a way to force the all occurences replacement?

Thanks

**Comment by rioj7** [comment]
@ziki77 It is a regex find/replace. You have to tell that you want to do this **`global`**.

Add this line to the `transform` arguments:

```
"flags": "g"
```

Another useful flag is `i` (find case insensitive)

**Comment by ziki77** [comment]
Hi, thanks for the answer! I missed the 'flag' argument!
