### ISSUE TITLE
Please add ${userHome}  to supported Variables

### ISSUE THREAD

**Issue by HofiOne** [rioj7/command-variable#42]
It is mentioned on the [Variables section](https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable#variables) that only a subset of VSC variables are implemented.

Please add the missing `${userHome}`.

Thanks!

**Comment by rioj7** [comment]
@HofiOne in v1.43.0 this variable is added

**Comment by HofiOne** [comment]
You are are GREAT! Thank you so much!
