### ISSUE TITLE
[Feature] change predefined folder of pickFile UI when path is too long

### ISSUE THREAD

**Issue by simon8233** [rioj7/command-variable#43]
I love this extension. it's fast and easily to use it.
Thanks for your help to reduce many effort 

I have suggestion for predefined options on pickfiles
https://github.com/rioj7/command-variable/blob/b1eaa1ae7884cb4441cb49e464b549a686ab9976/extension.js#L455

because codebase path is too long and predefined use vscode.window.showQuickPick to show it.

It will cause user can not get clear information from predefined path list.

is it possible when string length more than 60 or 80 charset . 

just show latest charset of predefined path or remove workspace path from label or add new field as label field 

example 
predefined path list : /proj/jonathan.chen/loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong_path/codebase/AAA/BBB/CCC/DDDD/EEEE/FFF/GGGGG/HHHH/IIII/JJJJ/KKKK/

action 1:  just show latest 60 or 80 charset 
show : 
ooooooooooong_path/codebase/AAA/BBB/CCC/DDDD/EEEE/FFF/GGGGG/HHHH/IIII/JJJJ/KKKK/

action 2:  remove workspace path from predefined path
show : 
AAA/BBB/CCC/DDDD/EEEE/FFF/GGGGG/HHHH/IIII/JJJJ/KKKK/

action 3 : add display label field , to let user control it

Very thanks for you reading.

**Comment by simon8233** [comment]
Thanks for your help.
I think **labelMaximumLength** and **transforms** is enough for customized usage
for `labelClipPoints `, I guess user can replace by `transforms `with `use Label` feature
Thanks your help again.

**Comment by rioj7** [comment]
@simon8233 have a look at v1.44.0

**Comment by simon8233** [comment]
Thanks , I will give a try ASAP :)
