### ISSUE TITLE
build error: Extension entrypoint(s) missing

### ISSUE THREAD

**Issue by GitMensch** [rioj7/command-variable#44]
~~~
$>git clone https://github.com/rioj7/command-variable
$>cd command-variable
$> vsce publish
 ERROR  Extension entrypoint(s) missing. Make sure these files exist and aren't ignored by '.vscodeignore':
  extension/out/extension-common.js
~~~

What parts are missing in these lines above?

**Comment by rioj7** [comment]
@GitMensch Before you publish you have to run the npm task `build`, this will create the file `out/extension-common.js`

**Comment by rioj7** [comment]
@GitMensch Does it help to publish this extension to open-vsx if I add the `prepublish` step to the `package.json`.

The doc for [`publish-extensions`](https://github.com/open-vsx/publish-extensions) does not tell how to configure this step in the extension repo.

**Comment by rioj7** [comment]
@GitMensch  Reading the doc page [extension_issues.md](https://github.com/open-vsx/publish-extensions/blob/master/docs/extension_issues.md) of the `open-vsx/publish-extensions` repo I think you can get it to work for open-vsx by adding the following JSON to 

`https://github.com/open-vsx/publish-extensions/blob/master/extensions.json`

```json
  "rioj7.command-variable": {
    "repository": "https://github.com/rioj7/command-variable",
    "prepublish": "npm run build"
  },
```
