### ISSUE TITLE
VSCode error "Cannot read properties of undefined (reading 'replace')" when using commandvariable.transform

### ISSUE THREAD

**Issue by daniel30hg** [rioj7/command-variable#49]
I checked the changelog, whatever this update did is now causing the command not to run:

```
[1.46.1] 2023-01-08
Fixed
transform : use of variables allowed in all properties
```

Simply using any transform input causes the task launch to instead display the error message "Cannot read properties of undefined (reading 'replace')".

For example, using ${input:gppExe} with:
```
"inputs":
[
	{
		"id": "gppExe",
		"type": "command", "command": "extension.commandvariable.transform",
		"args": { "text": "C:\\TDM-GCC-64\\bin\\g++.exe" }
	}
]
```

I rolled back to 1.46.0.

**Comment by rioj7** [comment]
@daniel30hg  try v1.46.2
lesson learned: **Even if you think your code change will not break a test, run the test suite**
