### ISSUE TITLE
Errors when using this extension with the remote tunnel feature

### ISSUE THREAD

**Issue by marcsandusky** [rioj7/command-variable#51]
The command variables are unable to be found when installed remotely on a tunnel connection.

Steps to duplicate:

* Run VSCode on a remote system and enable the remote tunnel feature
* Run VSCode on local system and enable the remote tunnel feature
* Establish a remote tunnel connection from the local system to the remote system
* Install the command variable extension onto the remote host
* Attempt to execute a task that uses one of the command-variable commands

The command variables are not found, even though the extension is remotely installed:
```none
2023-02-08 17:49:26.914 [error] command 'extension.commandvariable.pickStringRemember' not found: Error: command 'extension.commandvariable.pickStringRemember' not found
    at v.k (vscode-file://vscode-app/c:/Users/marc_/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1552:2618)
    at v.executeCommand (vscode-file://vscode-app/c:/Users/marc_/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1552:2534)
```
I plan on executing a similar test with remote WSL and Docker containers to determine if it is a general remote execution issue.

**Comment by rioj7** [comment]
@marcsandusky 
Have you examined the things mentioned in: [Incorrect execution location](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location)

**Comment by marcsandusky** [comment]
@rioj7 
After further testing, I have discovered that the issue only occurs when using code-insiders. After dealing with so many temporary broken issues, I switched to the standard version of code for my development. This is just one of many issues that were not working under code-insiders. I'm assuming it is a broken or updated API issue.

**Comment by rioj7** [comment]
@marcsandusky VSC-insiders is the development release of VSC, do not expect all things to work perfect, it allows users to try the new stuff and report possible problems.

If you encounter something that does not work in VSC-insiders create an issue at the VSC repo. Especially if it works in the regular VSC.
