### ISSUE TITLE
filterSelection doesn't work

### ISSUE THREAD

**Issue by cadem** [rioj7/command-variable#55]
I want to get a part of path, so I write the following setting, but it doesn't work. How I can fix this?

```json
        {
          "id": "testType",
          "type": "command",
          "command": "extension.commandvariable.transform",
          "args": {
            "text": "${relativeFile}",
            "separator": "\/",
            "filterSelection": "index===1"
          }
        }
```

**Comment by rioj7** [comment]
@cadem 

Explain in more detail what your setup is in VSC before you call a task or launch?

What is the need to use the second selected text?
If you only use 1 selection what is the need of the separator?

For which file do you need the relative path?

**Comment by cadem** [comment]
@rioj7 The following is my launch.json. ${relativeFile} is like tests/xxxx/yyyy.py. I want to get xxxx as ${input:fileName} and get yyyy.py as ${input:testType} from ${relativeFile}. So I use filterSelection as my solution, but it doesn't work.

{
    "version": "0.2.0",
    "configurations": [
        {
            "cwd": "${workspaceFolder}/tests/${input:testType}",
            "name": "Python: current file",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/tests/${input:testType}/testFramework.py",
            "args" : ["-testFile", "${input:fileName}"],
            "console": "integratedTerminal"
        }
    ],
    "inputs": [      
        {
          "id": "fileName",
          "type": "command",
          "command": "extension.commandvariable.transform",
          "args": {
            "text": "${relativeFile}", 
            "separator": "\/",
            "filterSelection": "index===2"
          }
        },
        {
          "id": "testType",
          "type": "command",
          "command": "extension.commandvariable.transform",
          "args": {
            "text": "${relativeFile}",
            "separator": "\/",
            "filterSelection": "index===1"
          }
        }
    ]
}

**Comment by rioj7** [comment]
@cadem `separator` is not a `split()` like functionality, it is used for the selected text to combine them just like `string::join()`

* Create a regex that matches the file path with capture groups for `xxxx` and `yyyy`: `^tests/(.+?)/(.+?\\.py)$`
* In the `replace` pick the capture group you want.

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "cwd": "${workspaceFolder}/tests/${input:testType}",
            "name": "Python: current file",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}/tests/${input:testType}/testFramework.py",
            "args" : ["-testFile", "${input:fileName}"],
            "console": "integratedTerminal"
        }
    ],
    "inputs": [      
        {
          "id": "fileName",
          "type": "command",
          "command": "extension.commandvariable.transform",
          "args": {
            "text": "${relativeFile}", 
            "find": "^tests/(.+?)/(.+?\\.py)$",
            "replace": "$2"
          }
        },
        {
          "id": "testType",
          "type": "command",
          "command": "extension.commandvariable.transform",
          "args": {
            "text": "${relativeFile}",
            "find": "^tests/(.+?)/(.+?\\.py)$",
            "replace": "$1"
          }
        }
    ]
}
```
