### ISSUE TITLE
Windows: uri.path returns inconsistent drive letter case which leads to 'File not in Multi-root Workspace' error

### ISSUE THREAD

**Issue by StefanRickli** [rioj7/command-variable#6]
### Description
While investigating a 'File not in Multi-root Workspace' error, I noticed that sometimes,
`editor.document.uri.path` returns the path with upper case drive letter and sometimes with lower case.
`workspaceFolder.uri.path` (which comes from `vscode.workspace.getWorkspaceFolder(editor.document.uri)`), always kept the drive letter lower case (at least in my test cases).

In the event that the drive letter's case differs, I get a 'File not in Multi-root Workspace' error because, for example, `documentPath.indexOf(rootPath)` performs a case sensitive comparison.

This behavior was triggered a lot when creating new files from within VS Code. Sometimes, deleting and restoring the file using Windows Explorer helped, sometimes I needed to restart VS Code, sometimes nothing would help. It has to do with how and when VSCode's file explorer generates these URIs, but we don't get any promises on the consistency of `uri.path` anyway.

### Possible Fix
A possible fix would be to naively perform a case insensitive string comparison (using `.toLower()`), or using `uri.fsPath`, which, according [to the documentation](https://vscode.readthedocs.io/en/latest/extensionAPI/vscode-api/#properties_79) (source code [here](https://github.com/microsoft/vscode/blob/54ac1f495179866acbbdbcb9d83e2885b5246874/src/vs/base/common/uri.ts#L579)), among other things, "normalize[s] windows drive letters to lower-case".

A quick search and replace of `uri.path` for `uri.fsPath` within `extension.js` fixed the issue for me in case when I was using `command:extension.commandvariable.file.relativeDirDots`. Of course, I'm not sure if it breaks something else. Haven't tested anything else yet.

**Comment by StefanRickli** [comment]
Okay, the proposed fix with `uri.fsPath` needs further elaboration since it uses platform specific path separators and thus breaks `relative_FileOrDirname_Posix`.

**Comment by rioj7** [comment]
I convert the driver letter to lower case when fetching the `uri.path`, also for the case where the file path result is Posix
