### ISSUE TITLE
Multiple choices checkboxes

### ISSUE THREAD

**Issue by daniel30hg** [rioj7/command-variable#60]
(sorry if this is not the appropriate place to ask for a feature request, but I couldn't find a more appropriate place)

Would it be possible to have a variable type, similar to "commandvariable.pickStringRemember", but where selecting multiple choices (instead of only one) is possible?

Basically, a list with checkboxes, such as:

> "Choose build options:"
> - [X] Debug _-g3_
> - [ ] Optimized _-O3_
> - [X] C++ 20 version _-std=c++20_

The selected options would then be concatenated, with a separator between them (e.g. "-g3 -std=c++20", if the separator is a space). Useful separators could be space " " to separate command arguments, and ampersands "&&" to run multiple commands.

Even better if you are able to specify which options can/can't be chosen together, for instance here you could only choose Debug or Optimized or neither, but not both.
And even better if the selected choices that were last selected come pre-selected.

**Comment by rioj7** [comment]
@daniel30hg  how would you go and pass the set of arguments to the command?
VSC will quote the arguments if they contain a space and also the command.

Have you looked at [Recently Used](https://marketplace.visualstudio.com/items?itemName=rioj7.vscode-recently-used) it allows you to create a number of Radio-button groups, it only allows 1 entry per group, add new entries during session, and remembers the previous selected option.

Or is a recently used behavior to `commandvariable.pickStringRemember` an option?

**Comment by daniel30hg** [comment]
> @daniel30hg how would you go and pass the set of arguments to the command? VSC will quote the arguments if they contain a space and also the command.

I personally pass the arguments of the task directly in the command itself:
![image](https://user-images.githubusercontent.com/95092963/232210006-782b56b3-24f6-4530-9823-e7e142eced1e.png)

And in inputs:
![image](https://user-images.githubusercontent.com/95092963/232210037-f0ac8b33-d4b5-4cab-be49-d5357d112414.png)


> Have you looked at [Recently Used](https://marketplace.visualstudio.com/items?itemName=rioj7.vscode-recently-used) it allows you to create a number of Radio-button groups, it only allows 1 entry per group, add new entries during session, and remembers the previous selected option.

That is not really what I am looking for though

> Or is a recently used behavior to `commandvariable.pickStringRemember` an option?

No, the "recently used" thing would be the cherry on top, it's not really the main feature.

**Comment by rioj7** [comment]
@daniel30hg It is possible to have a multi select pick list, the checkboxes is a much asked API but only available to the VSC core team.

The `pickStringRemember` will have

* a property to switch to multi select mode
* a property for the separator
* if you give it a key for remember it will remember the previous selected options, if the values are unique, it stores the selection in a different key (additional invalid characters), the given key will store the concatenated result
* assign an item to a radio button group

We don't have validation during selection, (`InputBox` has validation during input and an error text next to the input box), we have to evaluate all constraints on accept the selection and reshow the pick list if some constraint violates. You get an error message describing the violation.

There is an option to get a callback on selecting an item, not sure if we get a callback on de-select (the state of the item is not part of the callback arguments), but validation and message generation during selection will create a flood of useless messages.

Do you have a syntax idea of how to describe the constraints, 3 out of 4, ...., part of that is de dependency of option X on options A.B.C

**Comment by daniel30hg** [comment]
> @daniel30hg It is possible to have a multi select pick list, the checkboxes is a much asked API but only available to the VSC core team.
>
> The `pickStringRemember` will have
> 
> - a property to switch to multi select mode
> - a property for the separator
> - if you give it a key for remember it will remember the previous selected options, if the values are unique, it stores the selection in a different key (additional invalid characters), the given key will store the concatenated result
> - assign an item to a radio button group
> 
> 
> We don't have validation during selection, (`InputBox` has validation during input and an error text next to the input box), we have to evaluate all constraints on accept the selection and reshow the pick list if some constraint violates. You get an error message describing the violation.

While that is not the best, it's fine.

> There is an option to get a callback on selecting an item, not sure if we get a callback on de-select (the state of the item is not part of the callback arguments), but validation and message generation during selection will create a flood of useless messages.

If you can control selection, you could automatically deselect an option if it is selected and it did not meet constraints? If it's not possible that's fine tho.

> Do you have a syntax idea of how to describe the constraints, 3 out of 4, ...., part of that is de dependency of option X on options A.B.C

I was thinking of making 3 json properties:
- "minimumCountInGroup": where you specify the list of options and the minimum amount that must be selected
e.g. { debug, release }, 1 _would force you to select at least 1 (either debug or release)_

- "maximumCountInGroup": where you specify the list of options and the maximum amount that can be selected
e.g. { debug, release }, 1 _would prevent you from selecting more than 1 (cannot choose both debug and release)_

- "dependsOn": where you specify the list of list of options that must be picked for this to be enabled, where the broader list are "and" conditions, and the inner lists are "or" conditions
e.g. { logging, debug } _means the option can only be chosen if both logging AND debug are selected_
e.g. { { logging, printing } } _means the option can be chosen with "logging" selected OR with "printing" selected_
e.g. { { logging, printing }, debug } _means the option can be chosen with "logging" selected OR with "printing" selected, but debug must be selected no matter what_

> With regard to the logging do you want to conditionally add a selected log-part option to the result **only** if option logging is selected?

I personally do not want logging. I would be extremely content with having a pop-up appear telling you which condition wasn't met.

> With the constraints you could add rules for an option group based on minimum and maximum number of items selected in this group. A radio group would have `min`, and `max` set to `1`.

Yeah, that's what I described above also.

**Comment by rioj7** [comment]
@daniel30hg 

Not logging in the extension but you talk about logging options:

> Running the program with logging printed out to the console or not (if yes, also control which parts of the logging are enabled e.g. database, calculations...)

Your `dependsOn` property uses labels/names for an item, are they part of the item description?
In your OP you talk about `C++ 20 version`. Is this a label/name used in the `dependsOn` property?

The picklist items are specified in groups and `minCount` and `maxCount` are properties of the group.

**Comment by daniel30hg** [comment]
> @daniel30hg
> 
> Not logging in the extension but you talk about logging options:
> 
> > Running the program with logging printed out to the console or not (if yes, also control which parts of the logging are enabled e.g. database, calculations...)

Oh, no no, it's just another bash argument "-logging" to pass to the program.

> Your `dependsOn` property uses labels/names for an item, are they part of the item description? In your OP you talk about `C++ 20 version`. Is this a label/name used in the `dependsOn` property?

The C++20 version would be one of the items. "C++ 20" might be the display name, with "-std=c++20" being what it converts to.
You could add a 3rd field "identifier" (on top of "display name" and "string replacement" to be able to refer to it, or simply use the display name if this identifier is not set.
Or making the user have to create a group would work too, where the name of group would provide the "identifier" for the item.

> The picklist items are specified in groups and `minCount` and `maxCount` are properties of the group.

Oh, sure, that works too I suppose.

**Comment by rioj7** [comment]
@daniel30hg

I will implement it first without the `dependsOn` property, 
I'm not happy with the syntax yet, it is not directly clear what these `{}` mean.
I'm a big fan of **Explicit is better than Implicit**

**Comment by daniel30hg** [comment]
> @daniel30hg
> 
> I will implement it first without the `dependsOn` property,

Sure, that's fine

>I'm not happy with the syntax yet, it is not directly clear what these `{}` mean. I'm a big fan of **Explicit is better than Implicit**

I mean I agree that it's not ideal, but the alternative would be to make your own algorithm to parse expressions such as "dependOn: ((logging || printing) && debug)". It would be cooler, but also more time consuming and much harder to test for.

**Comment by rioj7** [comment]
@daniel30hg  Try v1.50.0, see the example for `multiPick` `pickStringRemember`

Reopen to keep track of: `dependsOn`

**Comment by daniel30hg** [comment]
A few problems:
![image](https://user-images.githubusercontent.com/95092963/233790276-902b7440-e750-4d4b-82bd-b1bf32915732.png)
![image](https://user-images.githubusercontent.com/95092963/233790282-b7009f82-cb32-4c10-ba8e-d7adf9d8746a.png)
It does not show me the options, nor does it allow me to pick multiple things.

Additionally, I am confused why it is developed this way: I wasn't expecting to have to define options within the options groups. I was expecting to have to reuse the options defined in "options", by specifying a list of labels in the optionGroups.
e.g.
```
"options": [ ["Debug", "-g3"], ["Release", "-O2"],
"optionGroups":
[
{ "label": "group1", "minCount": 1, "maxCount": 1, "options": [ "Debug", "Release" ] }
]
```
The reason I expected it to be done that way, is because as it stands it is impossible (?) to make 1 option belong to 2 groups at once (unless you are detecting identical duplicate options? which seems a bit annoying if you ever choose to modify an option).

**Comment by rioj7** [comment]
@daniel30hg 

Do you have **v1.50**. You can force VSC to update extensions.

If an option can belong to 2 groups I have to (un)check the other item, **which I can't**, if you (un)check an item. Now you don't have to get the labels consistent. An options always belongs to 1 and only 1 group. Selection is stored/restored based on processed (variables) label value.

**Comment by daniel30hg** [comment]
> @daniel30hg
> 
> Why do you post images of text? Copy/Paste is simpler. and easier if I want to recreate your setup.

It's faster for me to screenshot, but yeah I understand.

> Do you have **v1.50**. You can force VSC to update extensions.

Oh, strange, I did install v1.50 but I guess it didn't auto-switch to it, my bad.
I updated to it now and yeah it seems to work fine.

> If an option can belong to 2 groups I have to (un)check the other item, **which I can't**, if you (un)check an item. Now you don't have to get the labels consistent. An options always belongs to 1 and only 1 group. Selection is stored/restored based on processed (variables) label value.

It doesn't seem like it's checking or unchecking anything automatically anyway on my end.

---

Another topic is auto-selection on opening the task: would it be possible to have this persist not only during the session, but across closing/reopening vscode?

**Comment by rioj7** [comment]
@daniel30hg 

With what method do you do the screen shots?

> It doesn't seem like it's checking or unchecking anything automatically anyway on my end.

Where would you expect automatic (un)check given a particular configuration?

> would it be possible to have this persist not only during the session

It is possible to have persistent storage, I will look into it. (Haven't used it before)

**Comment by daniel30hg** [comment]
> @daniel30hg
> 
> With what method do you do the screen shots?

ShareX (program)

> > It doesn't seem like it's checking or unchecking anything automatically anyway on my end.
> 
> Where would you expect automatic (un)check given a particular configuration?

Well if the minimum and maximum is 1 for a group, I would expect whatever option is checked to be unchecked when I click something else in the group.
In general, if the maximum of a group is hit, I would expect the first option hit in that group (you would have to record the order in which you check things) to be unchecked.
And in general, if the minimum of a group is hit, I would expect it to re-check whatever you just unchecked.

> > would it be possible to have this persist not only during the session
> 
> It is possible to have persistent storage, I will look into it. (Haven't used it before)

Nice :)

**Comment by rioj7** [comment]
@daniel30hg Try v1.51.0 for `dependsOn`

**Comment by daniel30hg** [comment]
I haven't used dependsOn yet, however, it seems the previously selected options are lost when you modify the tasks.json file, even if you don't modify the pickStringRemember input.
They do persists through closing and reopening VSCode though, which is very nice!

Also, auto-deselecting is not working for me if it is intended to be in the commit.

**Comment by rioj7** [comment]
@daniel30hg  auto deselect is not intended and I can't do it,
Where would you expect auto-deselect?

> previously selected options are lost when you modify the tasks.json file

I don't see that behavior even when I modify the values of the `pickStringRemember`, the multi-pick is stored using the `key` property and the label values. Does it also happen when you use `"multiPickStorage": "global"`?

**Comment by rioj7** [comment]
@daniel30hg  Give the `pickStringRemember` a unique `key` property, the default value for `key` is `pickString` so all multi pick `pickStringRemember`'s are stored using the same key.

Just tried with 2 identical `pickStringRemember` but with different `key` property and it retains 2 sets of multi-pick options.

This gave the idea to allow variables in the `key` property. You can then create a `pickStringRemember` that picks a `key` value and that key-value is picked up in the big `pickStringRemember` as `"key": "${remember:my-multipick-key}`. This allows you to keep track of a set of multi pick options that you use often.

**Comment by daniel30hg** [comment]
> @daniel30hg Try v1.51.0 for `dependsOn`

I've tried it, it does not seem to work:
```
{
	"id": "tests",
	"type": "command", "command": "extension.commandvariable.pickStringRemember", // Need extension "Command Variable"
	"args":
	{
		"key": "tests",
		"description": "Choose tests and options",
		"multiPick": true,
		"optionGroups":
		[
			{ "label": "Diff tests", "name": "diffTests", "maxCount": 1, "options": [ ["Test 1", "first.sh"], ["Test 2", "second.sh"] ] },
			{ "label": "Diff options", "dependsOn": "diffTests", "options": [ ["Compile", "--compile"] ] }
		]
	}
}
```

![image](https://user-images.githubusercontent.com/95092963/234589069-275a8121-d94b-4ec7-843a-c49b92d034e9.png)
![image](https://user-images.githubusercontent.com/95092963/234589137-e1de226d-546e-4799-ae80-075cb3e4f187.png)

The "dependsOn" attribute does not prevent "--compile" from being selected, it merely prevents it from showing up instead.
I suppose that can be a nice behavior in many cases, but perhaps adding an option to alter the behavior to "do not accept combination if the dependency isn't selected" would be nice?

**Comment by daniel30hg** [comment]
Oh okay

I was saying to make it act like group minCount and maxCount though, where it gives you an error and just tells you to go re-select stuff

But either way, it works fine, thanks!
