### ISSUE TITLE
Picking one value from array defined in json/settings

### ISSUE THREAD

**Issue by TCI-Radek** [rioj7/command-variable#61]
Sorry to bother with probably silly question.
I am trying to use filecontent or expression for following scenario:

I have a json file like below.
Is it possible to define input for task so it will show me list of all server names to pick from?
(list of the servers is obviously fluid/variable)

Like:
S1T
S2T
S1P
S2P

`config.json / settings.json`

```json
{
    "Servers": [
        {
            "name": "S1T",
            "description": "Server Test 1",
	    "port": "1234"
        },
        {
            "name": "S2T",
            "description": "Server Test 2",
	    "port": "1235"
        },
        {
            "name": "S1P",
            "description": "Server Prod 1",
	    "port": "1236"
        },
        {
            "name": "S2P",
            "description": "Server Prod 2",
	    "port": "1237"
        }
    ]
}
```

**Comment by rioj7** [comment]
@TCI-Radek 

If I understand correct you would like the items (label,value,...) of a `pickStringRemember` to be extracted from a JSON file, extracted from one of the arrays. Based on expressions to select the data for an item property?

Currently you can use file content but each line represents an item.

I can make it so it can read the items from a JSON file using JavaScript expressions.

For your example the expressions could be:

```none
"label": "content.Servers[itemIdx].name",
"description": "content.Servers[itemIdx].description",
"value": "content.Servers[itemIdx].port"
```

You can write the expressions such that the `pickStringRemember` returns the server name or server port.

**Comment by TCI-Radek** [comment]
I think my need is even simpler than you think :)

Maybe I should start from what I want to achieve...
I want to create a task which will become part of repository. This repository may be cloned by many people - with different settings related to the list I am focused on ("servers" in the example above). So there is no  way to predict what servers are defined in the settings.
However my task(s) supposed to read the list of those servers and ask user a question: 
"which server you want to execute the action with?"
the action itself is not an issue - it could be restart/connect/etc - I just need the pickup selection to be dynamic - based on whatever is defined in settings/config json file.

I have a feeling that your extension can do this - but it is not obvious to me how, or my feeling is not correct :)

For example - as an extremely ugly overkill - I could achieve this by telling users:
_there is an directory in the repo called "yourServers" (ignored by git),  you need to put there files with names matching your server names - and the task will list those filenames as a selection for selecting server._

And then I could use "Pick File" option of your extension to create a pickup string - but I really hate this idea - and I would prefer to use json file as source of pickup string.

**Comment by rioj7** [comment]
@TCI-Radek  Have  a try with v1.52.0.

With the implemented method you can generally process any JSON content.

The example from the README:

----

The servers are specified in **servers.json** that is in the root of the workspace:

```json
{
  "Servers": [
    {
      "name": "S1T",
      "description": "Server Test 1",
      "hostname": "st001.test.mycomp.com",
      "port": "1234"
    },
    {
      "name": "S2T",
      "description": "Server Test 2",
      "hostname": "sq003.test.mycomp.com",
      "port": "1235"
    },
    {
      "name": "S1P",
      "description": "Server Prod 1",
      "hostname": "spab.mycomp.com",
      "port": "1236"
    },
    {
      "name": "S2P",
      "description": "Server Prod 2",
      "hostname": "sdef01.cs.mycomp.com",
      "port": "1237"
    }
  ]
}
```

In **tasks.json**:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Get server progress",
      "type": "shell",
      "command": "progress --server ${input:selectServer} --host ${input:server-hostname} --port ${input:server-port}"
    }
  ],
  "inputs": [
    {
      "id": "selectServer",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "description": "Which server?",
        "key": "server-name",
        "fileName": "${workspaceFolder}/servers.json",
        "fileFormat": "json",
        "jsonOption": {
          "label": "content.Servers[__itemIdx__].name",
          "description": "content.Servers[__itemIdx__].description",
          "value": {
            "server-name": "content.Servers[__itemIdx__].name",
            "server-hostname": "content.Servers[__itemIdx__].hostname",
            "server-port": "content.Servers[__itemIdx__].port"
          }
        }
      }
    },
    {
      "id": "server-hostname",
      "type": "command",
      "command": "extension.commandvariable.remember",
      "args": { "key": "server-hostname" }
    },
    {
      "id": "server-port",
      "type": "command",
      "command": "extension.commandvariable.remember",
      "args": { "key": "server-port" }
    }
  ]
}
```

----

You can simplify it as you want.

If you only want the server name you can use:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Get server progress",
      "type": "shell",
      "command": "progress --server ${input:selectServer}"
    }
  ],
  "inputs": [
    {
      "id": "selectServer",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "description": "Which server?",
        "key": "server-name",
        "fileName": "${workspaceFolder}/servers.json",
        "fileFormat": "json",
        "jsonOption": {
          "description": "content.Servers[__itemIdx__].description",
          "value": "content.Servers[__itemIdx__].name"
        }
      }
    }
  ]
}
```

**Comment by TCI-Radek** [comment]
absolutely fantastic! 
works as a charm now
thank you :)
