### ISSUE TITLE
Remember last value of promptString as "default" value

### ISSUE THREAD

**Issue by KlsBecker** [rioj7/command-variable#62]
Hello!

I have a doubt about this extension.

There is a way when the last value of the promptStringRemember shows as the default value when calling this again?
If I never use this key before, I want to define a default value that appears pre-selected in the prompt.
But, if the key has a value, it appears as pre-selected in the prompt and can only overwrite with the new one.

I have to use this feature with the [Memento Inputs](https://marketplace.visualstudio.com/items?itemName=spadin.memento-inputs) extension, but in my new project I need to pass a remembered value from task.json to launch.json and the extension doesn't have support to this.

Thus, I find this new extension that supplies me with perfection, but I miss the feature comment above. 

Does this extension support this?

**Comment by fstanley** [comment]
+1. I came here looking for the same feature. 
Default is already a key, but it does not substitute variables. In this example, the default value will just become "${input:rememberPath}"

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Task 1",
      "type": "shell",
      "command": "echo ",
      "args": ["-p", "${input:promptPath}"]
    },
    {
      "label": "Task 2",
      "type": "shell",
      "command": "echo ",
      "args": ["-p", "${input:rememberPath}"]
    },
    {
      "label": "Do Task 1 and 2",
      "dependsOrder": "sequence",
      "dependsOn": ["Task 1", "Task 2"],
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "promptPath",
      "type": "command",
      "command": "extension.commandvariable.promptStringRemember",
      "args": {
        "key": "path",
        "description": "Enter a path",
        "default": "${input:rememberPath}"
      }
    },
    {
      "id": "rememberPath",
      "type": "command",
      "command": "extension.commandvariable.remember",
      "args": { "key": "path" }
    }
  ]
}
```

**Comment by fstanley** [comment]
I managed to get this working with a simple fix, but I am not a JS developer, so I'll leave the patch here
```diff --git a/extension-common.js b/extension-common.js
index 0ed30da..e1945b3 100644
--- a/extension-common.js
+++ b/extension-common.js
@@ -369,7 +369,7 @@ async function promptStringRemember(args) {
   let result = await vscode.window.showInputBox({
       prompt: utils.getProperty(args, 'description', 'Enter:'),
       password: utils.getProperty(args, 'password', false),
-      value: utils.getProperty(args, 'default')
+      value: getRememberKey(utils.getProperty(args, 'key', 'promptString'),'__undefined') || utils.getProperty(args, 'default')
   });
   args.key = utils.getProperty(args, 'key', 'promptString');
   result = storeStringRemember2(args, result, false);
```

**Comment by rioj7** [comment]
fixed in 6de6c5b

**Comment by rioj7** [comment]
@KlsBecker  @fstanley 

Try v1.52.1.

You must set a `key` property, otherwise you get the value of another `promptStringRemember` if you have multiple unnamed input cases.

I don't know if you can transfer inputs/choices from a task-input to a launch-input.
I have the impression that before the `preLaunchTask` is called: ALL the variables in the launch config are resolved.
You can create a `pickStringRemember` that has as options:
* a `${remember}` variable
* a `${promptStringRemember}` variable

And set the property `empty` to return an empty string, but it stores the entered value using the `key` in the remember store.

In the `task.json` you use `commandvariable.remember` command to get value for given key.

**Comment by rioj7** [comment]
@fstanley I can't support variable `${input:rememberPath}` because I don't know what the source of the call is, task, launch, key binding, and if it is a Global/User, MultiRootWorkspace or Folder task/launch

**Comment by fstanley** [comment]
Looks good, works for me. Thanks

**Comment by KlsBecker** [comment]
Thanks for adding this feature! It worked perfectly for me.
