### ISSUE TITLE
promptStringRemember store folder 

### ISSUE THREAD

**Issue by diegofazio** [rioj7/command-variable#63]
I have different visual studio code installations using the same project.
I want to share between those machines the `promptStringRemember` values.
How can I set the file where this values are store to an specific folder inside my project?

**Comment by rioj7** [comment]
@diegofazio

`promptStringRemember` does not store the things it remembers in a file. It is remembered in memory.
If you close VSC all it has remembered for the various keys is lost.

The only thing stored persistent is the multi pick choice of `pickStringRemember`.
It is stored in some persistent storage for this VSC installation. You can't share it for other VSC installs.

What you want is to save and load the content of the remember store on close and open of VSC.
This can be stored in the `.vscode` folder of the workspace.
Are there times these VSC instances are running at the same time?
If so it needs a global store outside VSC running in the OS and you need to take care of simultaneous access. A lot of work and I don't get stuff working for all OS's supported by VSC.

If the nature of the strings is usually 1 out of a collection of fixed values you can use `pickStringRemember`, it can read the options from a file, JSON or using a pattern for each line.

I will see it I can load/save the content of the remember-store. Using a setting that specifies the file name to use (JSON). If you define that setting in your Folder/Workspace `settings.json` it won't affect other projects.

**Comment by diegofazio** [comment]
Hi, For example I looking for something **simple** to set my project version inside a file in my workspace. So I need to vscode ask me for that number( the version) remembered, calling a task, and then use the number as a param to injected in my code with a command. This solution you said could be what I looking for...
_"Using a setting that specifies the file name to use (JSON). If you define that setting in your Folder/Workspace settings.json it won't affect other projects."_

That will be great!. If it store the path of the json which store the vars in my .vscode folder each project could have theirs. I don't have simultaneous access to the same project, so, no problem.

Thanks 
Diego.

**Comment by rioj7** [comment]
@diegofazio 

Have you looked at the command `extension.commandvariable.file.content`?
It can read key-value files, JSON, YAML.

> and then use the number as a param to injected in my code with a command

What do you mean with **code**?
Do you mean the actual Python, C++,JavaScript file or the `tasks.json` or `launch.json` file?

**Comment by diegofazio** [comment]
I Meant my .c files. 
Yes, I tried with .file.content, but I want that when I run the task vscode ask me for the new value( using as default the one read in file ), like promptStringRemember does.

Diego.

**Comment by rioj7** [comment]
@diegofazio  In the compile task you define a preprocessor macro using the value from `promptStringRemember`?

I have to do it all synchronous. I write the file in the `deactivate` method of the extension, and this is a non-async function. And that means it will not work with remote file systems. I don't know which part of VSC is still working. NodeJS is working, so I have to use the `fs` module.

**Comment by rioj7** [comment]
@diegofazio  try v1.53.0

Use setting: `commandvariable.remember.persistent.file`
Example value: `${workspaceFolder}${pathSeparator}.vscode${pathSeparator}remember.json`

**RESTART VSC** on change of setting.
