### ISSUE TITLE
Support resolving settings configuration variables in input commands.

### ISSUE THREAD

**Issue by noahrondeau** [rioj7/command-variable#64]
Hello,
In the course of writing some tasks and launch configurations, I found that when I have a configuration variable in settings (either user settings, workspace settings, etc), those variables are not resolved in argument strings for input commands (e.g. `extension.commandvariable.file.pickFile`).

## Example

Here is an example. I have the following test workspace:

```json
{
  "folders": [
    {
      "path": "./test_workspace_folder"
    }
  ],
  "settings": {
    "TEST_DIR_NAME": "test_dir"
  },
  "tasks": {
    "version": "2.0.0",
    "tasks": [
      {
        "label": "Test Task - Echo File Content",
        "command": "cat '${input:input_test_file}'",
        "type": "shell",
        "isBackground": false,
        "presentation": {
          "echo": true,
          "reveal": "always",
          "focus": true,
          "panel": "shared",
          "showReuseMessage": true,
          "clear": false
        },
        "problemMatcher": []
      }
    ],
    "inputs": [
      {
        "type": "command",
        "id": "input_test_file",
        "command": "extension.commandvariable.file.pickFile",
        "args": {
          "include": "**/*",
          "exclude": "null",
          "display": "fileName",
          "fromFolder": {
            "fixed": "${workspaceFolder:test_workspace_folder}/test_dir"
          }
        }
      }
    ]
  }
}
```

In the "inputs" section, the `input_test_file` input uses a "fromFolder" "fixed" string saying where to grab look for files, here in the directory `test_dir`.

### Baseline Example (no config variable usage)

There is a config variable in settings called "TEST_DIR_NAME" set to "test_dir", but it is not referenced yet in this baseline example.

If I run the task, it works as intended. The test file is found, and the file content gets output to stdout:

<img alt="image" src="https://github.com/rioj7/command-variable/assets/9671728/22c8ec89-a22e-4105-a344-dff8d444ba72"/>

<img alt="image" src="https://github.com/rioj7/command-variable/assets/9671728/567cde55-cab0-4614-90ee-949b2d0ba68b"/>

<img alt="image" src="https://github.com/rioj7/command-variable/assets/9671728/d1916cbf-ee7a-44b3-90c8-75e1e8b4a093"/>

### Using the Config variable

If I now swap the "test_dir" name in the "fromFolder.fixed" field, like this:

```
"fromFolder": {
    "fixed": "${workspaceFolder:test_workspace_folder}/${config:TEST_DIR_NAME}",
},
```
Then, when I run the task, instead of seeing a drop down, it appears to not be able to resolve the path and nothing is populated in the pickFile dropdown:

<img alt="image" src="https://github.com/rioj7/command-variable/assets/9671728/1c18a13a-7c65-4500-a016-951a6744535e"/>

No amount of typing names in the 

### Desired behaviour 

Ideally, it would be great if the command inputs supplied by command variable were able to resolve the `${config:__}` syntax. Built-in task and launch input types provided by VS Code, such as `pickString` and `promptString` do resolve it correctly.

This is motivated because in the project where I'm using this as part of a shared workspace template with other developers, I am using config variables to denote file paths specific to the project, and I'm forced to use the built-in pickString option and supply all possible files instead of relying on the auto-population feature of pickFile, which I'd love to be able to do. This means I have to maintain the list of files actively as other developers add files. For context, the files in question are combinatorial flavours of build outputs, which makes keeping track of them all quite hard without the auto-populate feature.

**Comment by rioj7** [comment]
@noahrondeau

The extension supports config variable but implements a more expressive version.

* the config variable to use can be constructed using variables like `pickStringRemember` or `promptStringRemember`
* with a JavaScript expression you determine what part of the config should be returned, can be constructed using variables.
* it assumes the config variable is part of a section, contains at least 1 `.`

```json
{
  "folders": [
    {
      "path": "./test_workspace_folder"
    }
  ],
  "settings": {
    "project.TEST_DIR_NAME": "test_dir"
  },
  "tasks": {
    "version": "2.0.0",
    "tasks": [
      {
        "label": "Test Task - Echo File Content",
        "command": "cat '${input:input_test_file}'",
        "type": "shell",
        "isBackground": false,
        "presentation": {
          "echo": true,
          "reveal": "always",
          "focus": true,
          "panel": "shared",
          "showReuseMessage": true,
          "clear": false
        },
        "problemMatcher": []
      }
    ],
    "inputs": [
      {
        "id": "input_test_file",
        "type": "command",
        "command": "extension.commandvariable.file.pickFile",
        "args": {
          "include": "**/*",
          "exclude": "null",
          "display": "fileName",
          "fromFolder": {
            "fixed": "${workspaceFolder}${pathSeparator}${configExpression:test_dir}"
          },
          "configExpression": {
            "test_dir": {
              "configVariable": "project.TEST_DIR_NAME",
              "expression": "content",
              "default": "test_dir"   
            }
          }
        }
      }
    ]
  }
}
```

If on the next run  you most likely want the same file you can use `pickStringRemember` :

```json
    "inputs": [
      {
        "id": "input_test_file",
        "type": "command",
        "command": "extension.commandvariable.pickStringRemember",
        "args": {
          "description": "Which test file to use?",
          "options": [
            ["Use previous file", "${remember:input_test_file}"],
            ["Pick test file", "${pickFile:pick_test_file}"]
          ],
          "rememberTransformed": true,
          "key": "input_test_file",
          "pickFile": {
            "pick_test_file": {
              "include": "**/*",
              "exclude": "null",
              "display": "fileName",
              "fromFolder": {
                "fixed": "${workspaceFolder}${pathSeparator}${configExpression:test_dir}"
              },
              "configExpression": {
                "test_dir": {
                  "configVariable": "project.TEST_DIR_NAME",
                  "expression": "content",
                  "default": "test_dir"   
                }
              }
            }
          }
        }
      }
    ]
```

You used tabs and spaces in your `.code.workspace` file.

**Comment by noahrondeau** [comment]
@rioj7 thanks for you detailed response.
I had seen the configExpression options in the docs, but I saw they do not support config variables that don't have at least one `.` in them. Since my variables do not have dots, unfortunately configExpression is not applicable to them.
However, I think I should be able to change the variables in question to use dots without affecting any other functionality. I'll try that. Please do consider supporting config variables without a dot in the future, as many settings do not use them.

**Comment by rioj7** [comment]
@noahrondeau I don't know any VSC config setting that has no dot. Using the VSC API I have to specify a section (A dot-separated identifier) and a subsection. The VSC team has more options. The first section is to prevent name clashes and is for extensions the short-name of the extension.

Are you mistaken them with environment variables?

In my comment I used the setting `project.TEST_DIR_NAME`.

What is the problem of putting your settings in a section.
