### ISSUE TITLE
feature request: "echo"

### ISSUE THREAD

**Issue by Spongman** [rioj7/command-variable#65]
Sorry if this already exists, but i'd like a command that just returns a fixed value.

something like, eg.
```
  "inputs": [
    {
      "id": "someVar",
      "type": "command",
      "command": "extension.commandvariable.return",
      "args": {
        "value": "foo"
      }
    }
  ]
```

**Comment by Spongman** [comment]
nevermind, it looks like this can already be done with a `transform` command.

thanks for this extension!

**Comment by rioj7** [comment]
@Spongman what is the advantage of returning a fixed string, you can just replace the `${input}` variable with that string

**Comment by Spongman** [comment]
And if ${input} occurs 100 times?
