### ISSUE TITLE
Cannot read properties `fsPath`

### ISSUE THREAD

**Issue by jeffmilanes** [rioj7/command-variable#67]
Hi @rioj7 

I got an error when using this updated package.

![Screenshot 2023-06-30 at 10 57 07 AM](https://github.com/rioj7/command-variable/assets/2756849/b209c252-d228-4d0a-b71b-4809c0aec6ac)

Previously it was working then after an update i got this error. Here's my implementation on `launch.json`

![Screenshot 2023-06-30 at 11 07 04 AM](https://github.com/rioj7/command-variable/assets/2756849/f0815181-c4f9-4258-bc88-4f5209dbc45e)

**Comment by rioj7** [comment]
@jeffmilanes 

It is always best to not include pictures of text.
I have to type it over and I'm not allowed to make a mistake.
And I think it is easier just copy/paste between triple backtick lines.

```none
 ```json
 "inputs": [
   {
     
   }
 ]
 ```
```

results in

```json
"inputs": [
  {
    
  }
]
```

It is not the reason but why do you have `"display": "fileName"` a property of the `pickFile` property?
It will **never** be used.
If you want it you have to set it as a property of the `config` property.

I will recreate your setup and try to replicate the error and find the reason.

**Comment by jeffmilanes** [comment]
My bad, i'm debugging it actually, here's the text version.

```json
"inputs": [
        {
            "id": "appEnvironment",
            "type": "command",
            "command": "extension.commandvariable.file.content",
            "args": {
                "fileName": "${pickFile:config}",
                "json": "content.appEnvironment",
                "pickFile": {
                    "config": {
                        "description": "Select the environment to debug",
                        "include": ".secrets/*.json",
                        "keyRemember": "secretsFile"
                    }
                }
            }
        }
    ],
```

**Comment by rioj7** [comment]
@jeffmilanes 

I have looked at the code and I missed a case, I never tested it without `fromFolder` or `fromWorkspace`, I will add some unit tests to prevent this from happening.

As a workaround, I will change it to use this as default, set the folder to use to the `"${workspaceFolder}"` variable:

```json
"inputs": [
        {
            "id": "appEnvironment",
            "type": "command",
            "command": "extension.commandvariable.file.content",
            "args": {
                "fileName": "${pickFile:config}",
                "json": "content.appEnvironment",
                "pickFile": {
                    "config": {
                        "description": "Select the environment to debug",
                        "include": ".secrets/*.json",
                        "keyRemember": "secretsFile",
                        "fromFolder": {
                          "fixed": "${workspaceFolder}"
                        }
                    }
                }
            }
        }
    ],
```

I will update the README too because the text there is misleading.

**Comment by rioj7** [comment]
@jeffmilanes can you try v1.54.1 without the `"fromFolder"` property (just rename it to `"XXfromFolder"` to try)

**Comment by jeffmilanes** [comment]
@rioj7 it's working now without `fromFolder`
