### ISSUE TITLE
file.content ignores default value when it fails to find a json property

### ISSUE THREAD

**Issue by axel-lebourhis** [rioj7/command-variable#68]
Hi !

I'm using latest version of the extension, 1.54.1 and it seems the file.content command with JSON property ignores the default value I set, when it fails to find a json property.
I have a platforms.json file structured like this:
```
{
    "platform1": {
        "property1": "foo",
        "property2": "bar"
    },
    "platform2": {
        "property1": "foo2"
    },
}
```
In my launch.json, I have a pickStringRemember to select either `platform1` or `platform2`.
Then I have my file.content command which searches for the `property2`, like the following:
```
"inputs": [
        {
            "id": "FindProperty2",
            "type": "command",
            "command": "extension.commandvariable.file.content",
            "args": {
                "fileName": "${workspaceFolder}/.vscode/platforms.json",
                "json": "content.${remember:Platform}.property2",
                "default": "xyz",
            },
        },
    ]
}
```
When I run my launch config, I get an error from the extension:
`SyntaxError: Unexpected token 'U', "Unknown" is not valid JSON`
So it looks like instead of selecting "xyz" as value, it still uses "Unknown" as default value.

Does it mean a JSON property must always exist ?

EDIT: fixed typos

**Comment by rioj7** [comment]
@axel-lebourhis 

I get errors like: `Unexpected token } in JSON at position 75` because you have `,`'s where they are not allowed by JSON.

My VSC signals them as an error.

If I fix these (3) the default value is returned for `platform2`. (I used the name from the `file.content` command)

**`.vscode/platforms.json`**

```json
{
  "platform1": {
      "property1": "foo1",
      "property2": "bar1"
  },
  "platform2": {
      "property1": "foo2"
  }
}
```

**Comment by rioj7** [comment]
@axel-lebourhis If you don;t select a platform the `remember` variable returns `Unknown`

**Comment by rioj7** [comment]
@axel-lebourhis 

Does it work for you if you select `platform1`?

----

If you don't select a platform the `remember` variable returns `Unknown` or `I don't remember`

If I don't pick a platform first (I had to disable persistent remember) I get the error: `commandvariable.file.content: Incomplete expression`

----

If the filename does not match I get: `Unexpected token U in JSON at position 0`

You say your filename is `platform.json` but the task uses `platforms.json`
