### ISSUE TITLE
get relative pathUp2

### ISSUE THREAD

**Issue by gbrueckl** [rioj7/command-variable#7]
is it possible the the full relative path up two levels?

e.g. if my current file is `/folder/second/third/file.txt`
I would like to get `/folder/second`

ideally there would be a solution similar to `extension.commandvariable.file.fileDirBasenameXUp` but returning the full path and not only the folder name X levels up

**Comment by rioj7** [comment]
@gbrueckl See the updated README

**Comment by gbrueckl** [comment]
awesome, works like a charm!
thanks for your quick response

**Comment by gbrueckl** [comment]
seems like extension.commandvariable.file.fileDirname1Up returns the full path, any way to also return the relative path from the workspace root?

**Comment by rioj7** [comment]
@gbrueckl Look at version 1.11

I found your comment by visiting the email related to my github account.

Always best to mention the person with `@` in your message. Most likely I get a notify on my github main page. (That I visit frequently)

**Comment by gbrueckl** [comment]
great, thanks again!
