### ISSUE TITLE
file open dialog

### ISSUE THREAD

**Issue by dyitzchaki-roku** [rioj7/command-variable#77]
In addition to the `pickFile` command, it would be useful to have a command to show a file open dialog, using the [window.showOpenDialog](https://code.visualstudio.com/api/references/vscode-api#window.showOpenDialog) API.

I actually thought that's what `pickFile` do on first read.

That was also requested in VSCode quiet a while ago: https://github.com/microsoft/vscode/issues/71461

**Comment by rioj7** [comment]
@dyitzchaki-roku  see v1.61.0

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "echo Open Dialog",
      "type": "shell",
      "command": "echo",
      "args": [
        "${input:openDialog}"
      ],
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "openDialog",
      "type": "command",
      "command": "extension.commandvariable.file.openDialog",
      "args": {
        "canSelect": "files",
        "defaultUri": "${workspaceFolder}",
        "filters": {
          "Images": ["png", "jpg"],
          "TypeScript": ["ts", "tsx"]
        }
      }
    }
  ]
}
```
