### ISSUE TITLE
ignore workspaceFolder error

### ISSUE THREAD

**Issue by dvirtz** [rioj7/command-variable#78]
I have several multi-root projects that have one shared folder and one folder which is unique to each project, so
```
project-1:               project-2:               project-3:
|- folder a              |- folder a              |- folder a
|- folder b.1            |- folder b.2            |- folder b.3
```
etc.
I want to have a task in the shared folder that gets the name of the unique folder so I apply a JavaScript expression that returns the first valid of `${workspaceFolder:b.1}`, `${workspaceFolder:b.2}`, `${workspaceFolder:b.3}`, etc.
This works but there's annoying `Workspace not found with name` notifications popping up.

Can you add an option to ignore those errors or can you think of a better way to achieve this?

**Comment by rioj7** [comment]
@dvirtz  try v1.61.1 and use 

```
${workspaceFolder:b.1:nomsg}
${workspaceFolder:b.2:nomsg}
${workspaceFolder:b.3:nomsg}
```

I'm curious about the JavaScript expression that you use? Do you do it in the `tasks.json` file or in the script that is started by the task?

**Comment by dvirtz** [comment]
Thanks @rioj7, that works.
The task I run is 
```
{
  "id": "uniqueFolder",
  "type": "command",
  "command": "extension.commandvariable.config.expression",
  "args": {
    "configVariable": "editor.fontSize",
    "expression": "['${workspaceFolder:b.1:nomsg}', '${workspaceFolder:b.2:nomsg}', '${workspaceFolder:b.3:nomsg}'].find(folder => folder != 'Unknown')",
  }
}
```
I hack `config.expression` for that. I couldn't find a better way to just run some JS expression with variable expansion.

**Comment by rioj7** [comment]
@dvirtz Users always find creative application of features.

I will add this to the README as a possible use case of variables.

I will make the `configVariable` property optional.

**Comment by rioj7** [comment]
@dvirtz  in v1.61.2 `configVariable` property is optional
