### ISSUE TITLE
file.content can't have empty default

### ISSUE THREAD

**Issue by dyitzchaki-roku** [rioj7/command-variable#80]
I'm trying to have `file.content` return an empty string in case the key isn't found by setting `"default": ""` but it still results in `"Unknown"`.
I think the line
```
      if (args.default) { result = args.default; }
```
in https://github.com/rioj7/command-variable/blob/master/extension.js#L609
should be replaced by
```
      if (typeof args.default !== 'undefined') { result = args.default; }
```

**Comment by dyitzchaki-roku** [comment]
Tried also setting the expression to
```
content.hasOwnProperty('key') ? content.key : ''
```
but that fails for the same reason due to the code
```
    if (value) { result = value; }
```
that rejects empty strings

**Comment by rioj7** [comment]
@dyitzchaki-roku try v1.61.2, empty string for expression/value/default will be the result
