### ISSUE TITLE
[OpenDialog] Using inside `command` part of task breaks path resolvement

### ISSUE THREAD

**Issue by ThaDaVos** [rioj7/command-variable#83]
I noticed in a sequence of tasks, that the remember value/input value gets concatenated for some reason when used as command value, please see an example `tasks.json` below, when you run the "Do Something with Path" task, the CWD get concatenated for some reason:
```json
{
  "version": "2.0.0",
  "inputs": [
    {
      "id": "selectDirectory",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "description": "Deploy to where?",
        "options": [
          ["Use previous directory", "${remember:deployDirectory}"],
          ["Pick directory", "${openDialog:deployDirectory}"]
        ],
        "default": null,
        "openDialog": {
          "deployDirectory": {
            "description": "Which directory?",
            "canSelect": "folders",
            "defaultUri": "C:\\temp",
            "keyRemember": "deployDirectory"
          }
        }
      }
    }
  ],
  "tasks": [
    {
        "label": "Task A",
        "command": "Write-Output",
        "type": "shell",
        "args": [
            "Selected '${input:selectDirectory}' for A"
        ]
    },
    {
      "label": "Do Something with Path",
      "dependsOn": ["Task A"],
      "command": "${input:selectDirectory}\\DoSomething.exe",
      "options": {
        "cwd": "${input:selectDirectory}"
      }
    }
  ]
}
```

**Comment by rioj7** [comment]
@ThaDaVos Can you give examples of what you see when you select the directory `c:\temp` on the first `selectDirectory` invocation and choosing the remember version for the others. What commands are executed and in which directory?

You don't show where CWD gets concatenated.

I will try to recreate but I want to be sure I see the same as you.

Which version of VSC are you using?

**Comment by ThaDaVos** [comment]
@rioj7 - I see the command path being duplicated - so when I select `C:\Temp` - it tries to execute `c:\temp\c:\temp\DoSomething.exe`, as follows:
![afbeelding](https://github.com/rioj7/command-variable/assets/5251028/76cbfc44-0587-47b5-b950-9cf7cc3ef77b)

> @ThaDaVos Can you give examples of what you see when you select the directory `c:\temp` on the first `selectDirectory` invocation and choosing the remember version for the others. What commands are executed and in which directory?

What do you mean with `choosing the remember version for the others`? I don't get a second select option, it just executes it.
It also happens without the `dependsOn` I just noticed - also, the use of `CWD` is inrelevant - without it, it just prepends the current directory, so smallest reproducable:
```json
{
  "version": "2.0.0",
  "inputs": [
    {
      "id": "selectDirectory",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "description": "Deploy to where?",
        "options": [
          ["Use previous directory", "${remember:deployDirectory}"],
          ["Pick directory", "${openDialog:deployDirectory}"]
        ],
        "default": null,
        "openDialog": {
          "deployDirectory": {
            "description": "Which directory?",
            "canSelect": "folders",
            "defaultUri": "C:\\temp",
            "keyRemember": "deployDirectory"
          }
        }
      }
    }
  ],
  "tasks": [
    {
      "label": "Do Something with Path",
      "command": "${input:selectDirectory}\\DoSomething.exe",
    }
  ]
}
```

About info:
```
Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.26063
```

**Comment by ThaDaVos** [comment]
I currently worked around it by using `Start-Process` instead of straight up the `.exe` as Command but wanted to let you know that something goes wrong there, and couldn't pin-point if it was VSC or the extension:
```json
    {
      "label": "Start Something",
      "command": "Start-Process",
      "type": "shell",
      "args": [
        "-FilePath",
        "${input:selectDirectory}\\DoSomething.exe",
        "-WorkingDirectory",
        "${input:selectDirectory}"
      ]
    }
```

**Comment by ThaDaVos** [comment]
And let's close the issue - seems to be an actual VSC bug as `Do Something with Path from PickString` also breaks, but using `${workspaceFolder}` in `Do Something with Path in workspace` does not...
```json
{
  "version": "2.0.0",
  "inputs": [
    {
      "id": "selectDirectory",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "description": "Deploy to where?",
        "options": [
          ["Use previous directory", "${remember:deployDirectory}"],
          ["Pick directory", "${openDialog:deployDirectory}"]
        ],
        "default": null,
        "openDialog": {
          "deployDirectory": {
            "description": "Which directory?",
            "canSelect": "folders",
            "defaultUri": "C:\\temp",
            "keyRemember": "deployDirectory"
          }
        }
      }
    },
    {
      "id": "pickADirectory",
      "type": "pickString",
      "description": "Pick a directory to use",
      "options": [
        "${userHome}",
        "${workspaceFolder}",
        "${cwd}",
        "C:\\Temp"
      ]
    }
  ],
  "tasks": [
    {
        "label": "Task A",
        "command": "Write-Output",
        "type": "shell",
        "args": [
            "Selected '${input:selectDirectory}' for A"
        ]
    },
    {
      "label": "Do Something with Path",
      "command": "${input:selectDirectory}\\DoSomething.exe",
    },
    {
      "label": "Do Something with Path in workspace",
      "command": "${workspaceFolder}\\DoSomething.exe",
    },
    {
      "label": "Do Something with Path from PickString",
      "command": "${input:pickADirectory}\\DoSomething.exe",
    }
  ]
}
```

**Comment by rioj7** [comment]
@ThaDaVos 

What I mean with `choosing the remember version for the others` is to pick the option `Use previous directory`.

Maybe they have fixed it recently but VSC did not support variables in the `inputs` property of `tasks.json`.
In the `command-inputs` using `command-variable` commands you can use variables because the extension supports them.

I think you don't get a second invocation of `pickStringRemember` because task `Do Something with Path` depends on `Task A` and that has to finish first before `Do Something with Path` is executed and its variables are resolved.

**Comment by ThaDaVos** [comment]
I've taken the issue to VSC itself, as it also happens with `pickString` when it's used inside the `command`
