### ISSUE TITLE
fileaskey wrong fired event

### ISSUE THREAD

**Issue by aabramychev** [rioj7/command-variable#84]
I have two programm:  myprog and secondprog

if the full patch to executable will contain myrpog like 
c:\projetcs\myprog\exe\myprog and
c:\projetcs\myprog\exe\secondprog

I have two programs: "myprog" and "secondprog". 
If the full path to the executable contains "myprog", such as 
"c:\projects\myprog\exe\myprog" and 
"c:\projects\myprog\exe\secondprog", 
 the arguments of "myprog" will always be resolved and secondprog will call with commandline of myprog...
 It seems like the search substring is in the path instead of the file name.

**Comment by rioj7** [comment]
@aabramychev  Have you read the doc for `fileAsKey`

>If you have files with the same name use part of the full path to select the correct one like "/dir1/main.py" and "/dir2/main.py".

for your case try: `exe/myprog` and `exe/secondprog`, these are the unique parts of the file path

**Comment by rioj7** [comment]
@aabramychev
Have you opened the exe files in the editor?
What do you want to do in the task, show part of your `task.json`.

**Comment by rioj7** [comment]
@aabramychev if you have new info re-open the issue
