### ISSUE TITLE
feature request transform as tmp file

### ISSUE THREAD

**Issue by lublak** [rioj7/command-variable#85]
Currently in need an option to use promptStringRemember and save it to a file and get a filepath back. The debugger needs a file not a text input.

From the example, it would be useful to somehow receive the promptText as a tmpfilepath.

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Task 1",
      "type": "shell",
      "command": "dostuff1",
      "args": ["-p", "${input:promptText}"]
    },
    {
      "label": "Task 2",
      "type": "shell",
      "command": "dostuff2",
      "args": ["-p", "${input:rememberText}"]
    },
    {
      "label": "Do Task 1 and 2",
      "dependsOrder": "sequence",
      "dependsOn": ["Task 1", "Task 2"],
      "problemMatcher": []
    }
  ],
  "inputs": [
    {
      "id": "promptText",
      "type": "command",
      "command": "extension.commandvariable.promptStringRemember",
      "args": {
        "key": "text",
        "description": "Enter a text"
      }
    },
    {
      "id": "rememberText",
      "type": "command",
      "command": "extension.commandvariable.remember",
      "args": { "key": "text" }
    }
  ]
}
```

**Comment by rioj7** [comment]
@lublak It would have been better if you write an API proposal with new syntax.

If I understand it you want to save the text entered in `promptStringRemember` in a file and return and remember the file path.

Possible syntax would be:

```json
  "inputs": [
    {
      "id": "promptText",
      "type": "command",
      "command": "extension.commandvariable.promptStringRemember",
      "args": {
        "key": "text",
        "description": "Enter a text",
        "saveFile": "${workspaceFolder}/.vscode/tmp-text.txt"
      }
    }
  ]
```

The user has to construct a file path to use.

When you use `${input:promptText}` you get a OS file system file path that contains the text in UTF-8 format.

It will also be implemented for `pickStringRemember`

**Comment by lublak** [comment]
@rioj7 sry.

Yes this would one solution. Another solution would be:
This would also be usefull

```json
  "inputs": [
    {
      "id": "promptText",
      "type": "command",
      "command": "extension.commandvariable.promptStringRemember",
      "args": {
        "key": "text",
        "description": "Enter a text",
      }
    },
    {
      "id": "textTmpFile",
      "type": "command",
      "command": "extension.commandvariable.file.save",
      "args": {
           "key": "text",
           "file": "${workspaceFolder}/.vscode/tmp-text.txt"
       }
    }
  ]
```

This might also be useful if you need it outside of the prompt.
That way it would be more modular.

**Comment by rioj7** [comment]
@lublak  Your `textTmpFile` input would duplicate the `promptStringRemember` behavior with the only difference that it saves to a file, why not add that feature to `promptStringRemember`. And it is not clear what is the GUI used to get the content of the file. Just like `key` is additional functionality of `promptStringRemember` to put the result in a semi persistent storage.

And when I save the file path the way it is done in `pickFile` you can use `transform` in `remember` to modify/pick parts of the path to use.

**Comment by rioj7** [comment]
@lublak 

> This might also be useful if you need it outside of the prompt.
> That way it would be more modular.

I don't get these remarks.

Does `file.save` have a `text` argument that is the content of the file?
If so I can add a `file` argument to `commandvariable.transform`.

What would be the functionality of `commandvariable.file.save`?

**Comment by lublak** [comment]
@rioj7 For me, it's perfectly adequate if it's prompt. But I've also thought a little further ahead if someone needs it to save the current file, for example. 

```json
  "inputs": [
    {
      "id": "textTmpFile",
      "type": "command",
      "command": "extension.commandvariable.file.save",
      "args": {
           "text": "${file}",
           "file": "${workspaceFolder}/.vscode/tmp-text.txt"
       }
    }
  ]
```

**Comment by lublak** [comment]
> @lublak
> 
> > This might also be useful if you need it outside of the prompt.
> > That way it would be more modular.
> 
> I don't get these remarks.
> 
> Does `file.save` have a `text` argument that is the content of the file? If so I can add a `file` argument to `commandvariable.transform`.
> 
> What would be the functionality of `commandvariable.file.save`?

a file arguemtn to the commandvariable.transform would be the same solution yes :)
I was just thinking about how to build it so that it would be useful for more than just prompts.

**Comment by rioj7** [comment]
@lublak  try v1.63.0

Only the `transform` command has the `saveToFile` property.

If you want to use any other command as file content you have to wrap it in a `transform` and use variables.

An example `input`:

```json
    {
      "id": "saveToFile",
      "type": "command",
      "command": "extension.commandvariable.transform",
      "args": {
        "saveToFile": "${workspaceFolder}/.vscode/temp-text.txt",
        "text": "${promptStringRemember:getContent}",
        "key": "tmpfile",
        "promptStringRemember": {
          "getContent": {
              "description": "What to store in the file",
              "key": "fileContent"
          }
        }
      }
    }
```

**Comment by lublak** [comment]
@rioj7 works fine :) ty!
