### ISSUE TITLE
The replacement for selected text does not work.

### ISSUE THREAD

**Issue by Jazzy411** [rioj7/command-variable#9]
Can you make it support of `${selectedText}` variable for `extension.commandvariable.transform`.

And in the description:

The variables that can be used in the text are:

* ${workspaceFolder} : the path of the folder opened in VS Code
* ${file} : the current opened file (the file system path)
* ${relativeFile} : the current opened file relative to workspaceFolder
* ${fileBasename} : the current opened file's basename
* ${fileBasenameNoExtension} : the current opened file's basename with no file extension

**Comment by rioj7** [comment]
@Jazzy411  Implemented and have a look at the README to see what extra you can do to filter the selections
