### ISSUE TITLE
Feature request: Custom `description` in `pattern` of `pickStringRemember`

### ISSUE THREAD

**Issue by calebchalmers** [rioj7/command-variable#90]
I have a `pickStringRemember` input which reads an SSH config for hosts to list as options. Currently, everything works well and the hosts are listed with their names as the label. However, I would like to set a custom description for each option to display its hostname/address.

My intended regex is: 
```regex
Host (\S*)\n.*?HostName (\S*)\n
```
where the first capture group is the label/value and the second is the description.

Note, this requires also requires the regex to span multiple lines. I'm not sure if this is currently supported, but one option would be to use "/[regex]/[flags]" syntax in the `regexp` argument. This would allow users to control this behaviour via `/s` and `/m`.

**Comment by rioj7** [comment]
@calebchalmers Can you give a dummy example of the SSH config and the resulting pick options

**Comment by rioj7** [comment]
@calebchalmers With the `${transform}` variable you can modify any string to any other string with regex

**Comment by rioj7** [comment]
@calebchalmers  you can try v1.65

from the doc page

----

You have a file **`ssh-config.txt`** in the root of the workspace where you specify a number of hosts you can use:

```txt
Host 1.1.2.3
    HostName Computer1
Host 1.2.2.3
    HostName Computer2
Host 1.3.2.3
    HostName Computer3
```

Maybe there are other attributes specified for each IP address.

In **tasks.json**:

```jsonc
{
  "version": "2.0.0",
  "tasks": [
    //....
  ],
  "inputs": [
    {
      "id": "selectServer",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "description": "Which server?",
        "key": "server-ip",
        "fileName": "${workspaceFolder}/ssh-config.txt",
        "pattern": {
          "regexp": "Host (\\S+?)\\n.*?HostName (\\S+?)(?:\\n|$)",
          "flags": "g",
          "match": "find",
          "option": {
            "label": "$2",
            "value": "$1",
            "description": "$1"
          }
        }
      }
    }
  ]
}
```

You can make the `value` property as complex as you want.

----

**Comment by calebchalmers** [comment]
@rioj7 Thanks for the update -- this is exactly what I was looking for!

A few notes about the example:

For the SSH config, somewhat confusingly, it's actually `Host` which specifies the alias while `HostName` is the real destination address. i.e.
```ssh-config
Host server1
    HostName 1.1.1.1
Host server2
    HostName 2.2.2.2
Host server3
    HostName 3.3.3.3
```

And for task config, I had to use the `gs` flags to match across lines ([example](https://regex101.com/r/Y3jNNC/1)). I also simplified the regex a bit:
```json
{
  "version": "2.0.0",
  "tasks": [
    //....
  ],
  "inputs": [
    {
      "id": "selectServer",
      "type": "command",
      "command": "extension.commandvariable.pickStringRemember",
      "args": {
        "description": "Which server?",
        "key": "server-ip",
        "fileName": "${workspaceFolder}/ssh-config.txt",
        "pattern": {
          "regexp": "Host (\\S+).*?HostName (\\S+)",
          "flags": "gs",
          "match": "find",
          "option": {
            "label": "$1",
            "value": "$2",
            "description": "$2"
          }
        }
      }
    }
  ]
}
```

Thanks again!

**Comment by rioj7** [comment]
@calebchalmers  AFAIK the Hostname is the human readable form, based on the C-API calls you make to get the info.

**Comment by calebchalmers** [comment]
@rioj7 I'm not sure about the C-API, but for SSH config files, [the properties are documented here](https://www.man7.org/linux/man-pages/man5/ssh_config.5.html). Specifically,

**Host**
>Restricts the following declarations (up to the next Host or Match keyword) to be only for those hosts that match one of the patterns given after the keyword.  If more than one pattern is provided, they should be separated by whitespace.  A single ‘*’ as a pattern can be used to provide global defaults for all hosts.  The host is usually the hostname argument given on the command line (see the CanonicalizeHostname keyword for exceptions).

**Hostname**
>Specifies the real host name to log into.  This can be used to specify nicknames or abbreviations for hosts. Arguments to Hostname accept the tokens described in the “TOKENS” section.  Numeric IP addresses are also permitted (both on the command line and in Hostname specifications).  The default is the name given on the command line.

**Comment by rioj7** [comment]
@calebchalmers  with the following config file v1.65/0 shows incorrect pick items

```ssh-config
Host Computer1
    Port 2322
    HostName 1.1.1.1
Host Computer2
    User daenerys
    HostName 2.2.2.2
Host Computer3
    HostName 3.3.3.3
Host *
    LogLevel INFO
Host Computer4
    HostName 4.4.4.4
```

To prevent this I have added a few properties to v1.65.1

```json
        "pattern": {
          "regexp": "Host (\\S+).*?HostName (\\S+)",
          "flags": "gs",
          "match": "split",
          "split-regexp": "^Host ",
          "split-flags": "gm",
          "option": {
            "label": "$1",
            "value": "$2",
            "description": "$2"
          }
        }
```
